# Form implementation generated from reading ui file 'uis/1.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(612, 364)
        MainWindow.setMinimumSize(QtCore.QSize(612, 364))
        MainWindow.setMaximumSize(QtCore.QSize(612, 364))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.table = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.table.setGeometry(QtCore.QRect(10, 10, 441, 341))
        self.table.setShowGrid(True)
        self.table.setGridStyle(QtCore.Qt.PenStyle.SolidLine)
        self.table.setColumnCount(5)
        self.table.setObjectName("table")
        self.table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table.setHorizontalHeaderItem(4, item)
        self.table.horizontalHeader().setVisible(True)
        self.table.horizontalHeader().setCascadingSectionResizes(False)
        self.table.verticalHeader().setCascadingSectionResizes(False)
        self.comboSchool = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboSchool.setGeometry(QtCore.QRect(460, 40, 69, 22))
        self.comboSchool.setToolTip("")
        self.comboSchool.setObjectName("comboSchool")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(460, 10, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(460, 80, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboClass = QtWidgets.QComboBox(parent=self.centralwidget)
        self.comboClass.setGeometry(QtCore.QRect(460, 110, 69, 22))
        self.comboClass.setToolTip("")
        self.comboClass.setObjectName("comboClass")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.table.setSortingEnabled(False)
        item = self.table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Логин"))
        item = self.table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "ФИО"))
        item = self.table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Суммарный балл"))
        item = self.table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Школа"))
        item = self.table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Класс"))
        self.label.setText(_translate("MainWindow", "Номер школы"))
        self.label_2.setText(_translate("MainWindow", "Номер класса"))
