# Form implementation generated from reading ui file 'uis/6_lib.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LibWindow(object):
    def setupUi(self, LibWindow):
        LibWindow.setObjectName("LibWindow")
        LibWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=LibWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 0, 781, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.searchTitle = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.searchTitle.setObjectName("searchTitle")
        self.horizontalLayout.addWidget(self.searchTitle)
        self.label_2 = QtWidgets.QLabel(parent=self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.searchAuthor = QtWidgets.QLineEdit(parent=self.horizontalLayoutWidget)
        self.searchAuthor.setObjectName("searchAuthor")
        self.horizontalLayout.addWidget(self.searchAuthor)
        self.table = QtWidgets.QTableView(parent=self.centralwidget)
        self.table.setGeometry(QtCore.QRect(10, 40, 781, 531))
        self.table.setObjectName("table")
        LibWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=LibWindow)
        self.statusbar.setObjectName("statusbar")
        LibWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LibWindow)
        QtCore.QMetaObject.connectSlotsByName(LibWindow)

    def retranslateUi(self, LibWindow):
        _translate = QtCore.QCoreApplication.translate
        LibWindow.setWindowTitle(_translate("LibWindow", "Library"))
        self.label.setText(_translate("LibWindow", "Title:"))
        self.label_2.setText(_translate("LibWindow", "Author:"))
