# Form implementation generated from reading ui file 'uis/6_lib.ui'
#
# Created by: PyQt6 UI code generator 6.9.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_LibWindow(object):
    def setupUi(self, LibWindow):
        LibWindow.setObjectName("LibWindow")
        LibWindow.resize(1051, 620)
        self.centralwidget = QtWidgets.QWidget(parent=LibWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.searchTitle = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.searchTitle.setObjectName("searchTitle")
        self.horizontalLayout.addWidget(self.searchTitle)
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.searchAuthor = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.searchAuthor.setObjectName("searchAuthor")
        self.horizontalLayout.addWidget(self.searchAuthor)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.table = QtWidgets.QTableView(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(16)
        self.table.setFont(font)
        self.table.setTextElideMode(QtCore.Qt.TextElideMode.ElideLeft)
        self.table.setObjectName("table")
        self.gridLayout.addWidget(self.table, 1, 0, 1, 1)
        LibWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=LibWindow)
        self.statusbar.setObjectName("statusbar")
        LibWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LibWindow)
        QtCore.QMetaObject.connectSlotsByName(LibWindow)

    def retranslateUi(self, LibWindow):
        _translate = QtCore.QCoreApplication.translate
        LibWindow.setWindowTitle(_translate("LibWindow", "Library"))
        self.label.setText(_translate("LibWindow", "Title:"))
        self.label_2.setText(_translate("LibWindow", "Author:"))
